"""
Stage 26 Training and Dataset Eligibility Package.
"""
from app.model_simplification.training.eligibility import (
    GroupSafeEligibilityAuditor,
    ALL_DISPOSITIONS,
    DISPOSITION_DIRECT_REFORMULATION,
    DISPOSITION_SOURCE_GROUP_REFORMULATION,
    DISPOSITION_NON_DEV_SPLIT,
    DISPOSITION_INCOMPLETE_GROUP,
    DISPOSITION_RIGHTS_GOVERNANCE,
    DISPOSITION_QUALITY_FAILED,
    DISPOSITION_MANUAL_REVIEW,
    DISPOSITION_ELIGIBLE_INTERNAL_TRAINING,
)

__all__ = [
    "GroupSafeEligibilityAuditor",
    "ALL_DISPOSITIONS",
    "DISPOSITION_DIRECT_REFORMULATION",
    "DISPOSITION_SOURCE_GROUP_REFORMULATION",
    "DISPOSITION_NON_DEV_SPLIT",
    "DISPOSITION_INCOMPLETE_GROUP",
    "DISPOSITION_RIGHTS_GOVERNANCE",
    "DISPOSITION_QUALITY_FAILED",
    "DISPOSITION_MANUAL_REVIEW",
    "DISPOSITION_ELIGIBLE_INTERNAL_TRAINING",
]
